language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script:
  - bundle exec rake spec
  - bundle exec cucumber
before_script:
  - mysql -e 'create database powerdns_test'
  - RAILS_ENV=test bundle exec rake db:setup --trace